name: Package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        # os: [macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Perl Stuff
      run: |
        env
        brew install pkg-config
        curl -L https://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
        eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
        env
        cpanm --info
        cpanm Config::Tiny
        perl ./test.pl
        which pp
        pp -o test ./test.pl
        ./test