name: Package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        # os: [macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Perl Stuff
      run: |
        brew install gd
        brew install pkg-config
        brew install cpanm
        cpanm --sudo --installdeps GD
        cpanm --sudo --installdeps POSIX
        cpanm --sudo --installdeps Config::Tiny
        cpanm --sudo --installdeps File::stat
        cpanm --sudo --installdeps Geo::ShapeFile
        cpanm --sudo --force --installdeps PAR
        cpanm --sudo --installdeps PAR::Packer
        perl ./test.pl
        which pp
        pp -o test ./test.pl
        ./test