name: Package

on: [push]

jobs:
  package-macOS:
    name: Package macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Brew Items
      run: |
        brew install bzip2 jpeg libpng pkg-config gd cpanm
    - name: Install Perl Modules
      run: |
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        cpanm GD
        cpanm POSIX
        cpanm Config::Tiny
        cpanm File::stat
        cpanm Geo::ShapeFile
        cpanm -f PAR
        cpanm PAR::Packer
    - name: Package
      shell: bash -v {0}
      run: |
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        pp -x -l gd -l bz2 -l fontconfig -l freetype -l gd -l jpeg -l lzma -l png16 -l tiff -l webp -o pullauta ./pullauta.pl
    - name: Upload macOS Build
      uses: actions/upload-artifact@v4
      with:
        name: pullauta-macos
        path: pullauta
        if-no-files-found: error

  build-linux:
    name: Package Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Apt Items
      run: |
        sudo apt install cpanminus libgd-dev libgd-perl libperl-dev libpng-dev libwebp-dev
    - name: Install Perl Modules
      run: |
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        cpanm GD
        cpanm POSIX
        cpanm Config::Tiny
        cpanm File::stat
        cpanm Geo::ShapeFile
        cpanm PAR
        cpanm PAR::Packer
    - name: Package
      shell: bash -v {0}
      run: |
        eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
        pp -x -l Xpm -l bz2 -l fontconfig -l freetype -l gd -l jbig -l jpeg -l lzma -l png16 -l tiff -l webp -o pullauta ./pullauta.pl
    - name: Upload Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: pullauta-linux
        path: pullauta
        if-no-files-found: error
