name: Package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        # os: [macOS-latest, ubuntu-latest]

    steps:
    - name: Install Perl Stuff
      run: |
        brew install gd
        brew install pkg-config
        brew install cpanm
        cpanm --installdeps GD
        cpanm --installdeps POSIX
        cpanm --installdeps Config::Tiny
        cpanm --installdeps File::stat
        cpanm --installdeps Geo::ShapeFile
        cpanm --force --installdeps Archive::Zip
        cpanm -v --installdeps PAR
        cpanm -v --installdeps PAR::Packer
        perl ./test.pl
